version: '3'
services:
  confluence:
    image: atlassian/confluence
    ports: 
      - 80:8090
    env_file: .env
    volumes:
      - cfs-home:/var/atlassian/application-data/confluence

volumes:
  cfs-home:
    driver_opts:
      type: "nfs"
      # addr需填写CFS的地址
      o: "addr=10.206.0.11,nolock,soft,rw"
      # 目录需填写CFS的命名空间
      device: ":/btnibh3a"
